### ISSUE TITLE
프로파일 분리

### ISSUE THREAD

**Issue by wonslee** [uswLectureEvaluation/SUWIKI-Spring#37]
프로파일을 **prod**(현재 운영 서버에 있는 YML 내용이 해당), **dev**(개발용 EC2, RDS, S3에서만 돌아감), local(로컬 컴퓨터)로 분리해서 

개발중에 운영 DB는 절대!! 건들지 않게 하려고 합니다
[참고: 조졸두님 블로그](https://jojoldu.tistory.com/269)

괜찮으시다면 프로파일 분리된거 반영되도록 EC2의 start.sh 수정해도 괜찮을까요? @K-Diger 
sh 파일에서 서버 시작시킬 때 프로파일 명시해주는 식으로 수정해야 할 것 같아요
(배포가 엄청 편하고 안전해질 것 같아요! ㅎㅎ.. 신경쓰이게 해서 죄송합니다
한다면 도현님 시간 괜찮으실 때 하겠습니다)

[제가 프로파일 명시했던 예시](https://github.com/Akatsuki-USW/Buzzzzing-Server/blob/develop/Dockerfile)

[application.yml 수정 예시](https://wonyong-jang.github.io/spring/2022/08/11/Spring-Profile.html)

### TODO
- [x] 프로파일 분리 및 해당 YML 설정 -> YML 공유
- [x] application.yml 반영 -> dev 용 CI CD 설정
- [x] main CI CD 구현 (start.sh 수정)

**Comment by K-Diger** [comment]
미뤄왔던 부채였는데 하하 ... 처리해주신다니 감사합니다. 아래는 제가 요즘 진행하는 활동에서 얻은 목표 설계 방식인데 참고해주셔도 좋을 것 같습니다!

### 마일스톤1 : 나의 100%의 역량

- 현재 ISSUE에 명시한 방법으로 프로파일 관리

### 마일스톤2 : 죽기 직전까지 했을 때

- Spring Cloud Config를 통해 모든 (Micro)서버가 Config서버를 통해 설정값을 가져온다.

### 마일스톤3 : 궁극의 단계

- API Gateway Pattern 을 활용한 MSA로 모듈간 의존성 분리

**Comment by wonslee** [comment]
와우 이건 뭔가요? 마일스통 2, 3은 조금 무섭네요ㅋㅋㅋㅋㅋ
혹시 레퍼런스 링크 공유해주실 수 있나요?
