### ISSUE TITLE
인수 테스트

### ISSUE THREAD

**Issue by wonslee** [uswLectureEvaluation/SUWIKI-Spring#76]
## 개요
희조님의 조언을 참고해서 인수 테스트(통합 테스트)를 하려고 합니다.  
제대로 된 통합 테스트는 처음 해보는지라 기간이 조금 걸릴 것 같습니다.  
그래도 제가 비즈니스 로직을 모두 이해하고 앞으로의 리팩토링 및 기능 추가를 안전하게 진행하려면 꼭 필요하다고 생각했습니다.  

## TODO
- [ ] 현재 통합 테스트 SQL -> JPA로 변경. 
- [ ] 로그인 로직 테스트 방법 공부
- [ ] 전반적인 기능 명세 작성 및 유저 시나리오 구성
- [ ] 각 도메인별 fixture 작업
- [ ] 기존 SQL 파일 방식에서 JPA 방식으로 리팩토링
- [ ] Jacoco 테스트 커버리지 확인

통합 테스트 목록
- [ ] 강의
- [ ] 시간표
- [ ] 전공 즐겨찾기
- [ ] 강의 평가
- [ ] 시험 평가
- [ ] 유저
- [ ] 공지사항
- [ ] 인증 토큰
- [ ] 블랙 리스트
